version: 2.1

#
# Constant definitions
#
constants:
  - &node-version 12.18.1

#
# Import orbs
#
orbs:
  node: circleci/node@4.0.1

#
# Workflow definitions
#
workflows:
  main:
    jobs:
      - lint
      - pack

#
# Jobs
#
jobs:
  lint:
    executor:
      name: node/default
      tag: *node-version
    steps:
      - checkout
      - node/install-packages
      - run:
          name: EsLint
          command: npm run eslint -- --format junit --output-file ./test-reports/eslint/results.xml
      - run:
          name: Prettier
          command: npm run prettier
      - store_test_results:
          path: ./test-reports
  pack:
    executor:
      name: node/default
      tag: *node-version
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Execute Webpack
          command: npx webpack
