version: 2.1

#
# Constant definitions
#
constants:
  - &node-version 14.15.4

#
# Import orbs
#
orbs:
  node: circleci/node@4.2.1

#
# Workflow definitions
#
workflows:
  main:
    jobs:
      - lint
      - package

#
# Jobs
#
jobs:
  lint:
    executor:
      name: node/default
      tag: *node-version
    steps:
      - checkout
      - node/install-packages
      - run:
          name: EsLint
          command: npm run eslint -- --format junit --output-file ./test-reports/eslint/results.xml
      - run:
          name: Prettier
          command: npm run prettier
      - store_test_results:
          path: ./test-reports
  package:
    executor:
      name: node/default
      tag: *node-version
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run package
          command: npm run package
